name: snappy_snag
description: "An easy-to-use in-app bug reporting and user feedback SDK for Flutter, allowing users to send screenshots, device info, and custom logs seamlessly."
version: 0.0.3
homepage: https://snappysnag.com?utm_source=pub_dev&utm_medium=referral&utm_campaign=package_sidebar
repository: https://github.com/snappysnag/snappy_snag_flutter
issue_tracker: https://github.com/snappysnag/snappy_snag_flutter/issues
topics:
  - bug-reporting
  - feedback
  - developer-tools
  - screenshot
  - ai


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  screenshot: ^3.0.0
  sensors_plus: ">=6.0.0 <8.0.0"
  http: ^1.2.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
